name: EssentialsKiller
version: 1.0
author: Maestro
main: eu.maestro.essentialskiller.EssentialsKillerPlugin
commands:
  ping:
    description: This command allows you to see your own ping or a specific player ping
    usage: /ping <player>
  spawn:
    description: Teleport to spawn
    aliases: [lobby, hub]
    usage: /spawn
  warp:
     description: idk how to define a warp bro
     aliases: [w, warps]
     usage: /warp <warp>
  back:
     description: last death
     aliases: [b]
     usage: /back
